name: ai_rap_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  auto_route: ^8.1.3
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_gemini: ^2.0.4
  flutter_onboarding_slider: ^1.0.11
  flutter_share: ^2.0.0
  fluttertoast: ^8.2.5
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^3.1.2
  path_provider: ^2.1.3
  provider: ^6.1.2
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.6

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  envy_generator: ^0.0.5
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter gen:
  output: lib/product/gen/
  integrations:
    lottie: true
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/inapp/
    - assets/images/onboarding/
    - assets/images/songs/
    - assets/images/beats/
    - assets/images/prompt/
    - assets/images/rapper/
    - assets/images/song/
    - assets/images/settings/
    - assets/lottie/

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: 'assets/fonts/poppins/Poppins-Regular.ttf'
    - family: Poppins-Black
      fonts:
        - asset: 'assets/fonts/poppins/Poppins-Black.ttf'
